name: Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.1
        with:
          ref: main
          fetch-depth: 0
          persist-credentials: false

      - name: Setup
        uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"

      - name: Build
        run: make release

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/*
          draft: true
          generate_release_notes: true
          body: |
            * 这是 GitHub Actions 自动化部署，更新日志应该很快会手动更新